version: '3.4'

services:

  db:
    build: .
    restart: always
    volumes:
      - db:C:\MSSQL    
    ports:
      - "51433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
  
  printer:
    image: ghcr.io/kreisverkehr/u-orders:print-edge
    restart: always
    environment:
      - Printer__Type=File
      - Printer__CodePage=858
#      - Printer__FilePath=/dev/usb/lp0
      - Printer__FilePath=/printstream.dat
      - Printer__Culture=de-DE
      - AuthSecret=ThisIsThePrinterSecret
#    devices:
#      - "/dev/usb/lp0:/dev/usb/lp0"

  service:
    image: ghcr.io/kreisverkehr/u-orders:service-edge
    restart: always
    environment:
      - Db__Provider=mssql
      - Db__Host=db
      - Db__Port=1433
      - Db__User=sa
      - Db__Password=yourStrong(!)Password
      - ADMIN_USER=admin
      - ADMIN_PASS=4u-Orders
    depends_on:
      - db
      - printer

  api:
    image: ghcr.io/kreisverkehr/u-orders:api-edge
    restart: always
    ports:
      - "8889:80"
    depends_on:
      - db
      - service
    environment:
      - Db__Provider=mssql
      - Db__Host=db
      - Db__Port=1433
      - Db__User=sa
      - Db__Password=yourStrong(!)Password
      - JWT__Secret=ThisIsTheWebApiSecret
      - Printer__Host=printer
      - Printer__Port=80
      - Printer__Lang=de
      - Printer__Secret=ThisIsThePrinterSecret
      - PRINT_SERVICE_HOST=printer
      - PRINT_SERVICE_PORT=80

  webui:
    image: ghcr.io/kreisverkehr/u-orders:web-edge
    restart: always
    ports:
      - "8888:80"
#    volumes:
#      - .\appsettings.json:C:\inetpub\wwwroot\wwwroot\appsettings.json
    depends_on:
      - api

volumes:
  db: