version: '3.4'

services:

  db:
    image: mysql:oracle
    restart: always
    volumes:
      - db:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devpwd
      - MYSQL_DATABASE=devdb
    networks:
      - backend
  
  printer:
    image: ghcr.io/kreisverkehr/u-orders:print-latest
    restart: always
    environment:
      - Printer__Type=File
      - Printer__CodePage=858
#      - Printer__FilePath=/dev/usb/lp0
      - Printer__FilePath=/printstream.dat
      - Printer__Culture=de-DE
      - AuthSecret=ThisIsThePrinterSecret
#    devices:
#      - "/dev/usb/lp0:/dev/usb/lp0"
    networks:
      - backend

  service:
    image: ghcr.io/kreisverkehr/u-orders:service-latest
    restart: always
    environment:
      - Db__Provider=mysql
      - Db__Host=db
      - Db__Port=3306
      - Db__User=dev
      - Db__Password=devpwd
      - Db__DbName=devdb
      - ADMIN_USER=admin
      - ADMIN_PASS=4u-Orders
    depends_on:
      - db
      - printer
    networks:
      - backend

  api:
    image: ghcr.io/kreisverkehr/u-orders:api-latest
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
      - service
    environment:
      - Db__Provider=mysql
      - Db__Host=db
      - Db__Port=3306
      - Db__User=dev
      - Db__Password=devpwd
      - Db__DbName=devdb
      - JWT__Secret=ThisIsTheWebApiSecret
      - Printer__Host=printer
      - Printer__Port=80
      - Printer__Lang=de
      - Printer__Secret=ThisIsThePrinterSecret
      - PRINT_SERVICE_HOST=printer
      - PRINT_SERVICE_PORT=80
    networks:
      - frontend
      - backend

  webui:
    image: ghcr.io/kreisverkehr/u-orders:web-latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./appsettings.json:/usr/share/nginx/html/appsettings.json
    depends_on:
      - api
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  db: