// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UOrders.EFModel;

#nullable disable

namespace UOrders.EFModel.Postgres.Migrations
{
    [DbContext(typeof(UOrdersDbContext))]
    partial class UOrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UOrders.EFModel.LocalizedText", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MenuCategoryDescriptionID")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuCategoryTitleID")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuItemDescriptionID")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuItemOptionDescriptionID")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuItemOptionNameID")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuItemOptionValueNameID")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuItemTitleID")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("MenuCategoryDescriptionID");

                    b.HasIndex("MenuCategoryTitleID");

                    b.HasIndex("MenuItemDescriptionID");

                    b.HasIndex("MenuItemOptionDescriptionID");

                    b.HasIndex("MenuItemOptionNameID");

                    b.HasIndex("MenuItemOptionValueNameID");

                    b.HasIndex("MenuItemTitleID");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("ToBeRemoved")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<bool>("ToBeRemoved")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuItemOption", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("MenuItemID")
                        .HasColumnType("integer");

                    b.Property<int>("OptionType")
                        .HasColumnType("integer");

                    b.Property<bool>("ToBeRemoved")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("MenuItemID");

                    b.ToTable("MenuItemOptions");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuItemOptionValue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("MenuItemOptionID")
                        .HasColumnType("integer");

                    b.Property<bool>("ToBeRemoved")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("MenuItemOptionID");

                    b.ToTable("MenuItemOptionValues");
                });

            modelBuilder.Entity("UOrders.EFModel.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("text");

                    b.Property<string>("OrderedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OrderedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReviewToken")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("OrderedById");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("UOrders.EFModel.OrderItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("MenuItemID")
                        .HasColumnType("integer");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("MenuItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("UOrders.EFModel.OrderItemCheckedOption", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("OptionValueID")
                        .HasColumnType("integer");

                    b.Property<int>("OrderItemID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("OptionValueID");

                    b.HasIndex("OrderItemID");

                    b.ToTable("OrderItemCheckedOptions");
                });

            modelBuilder.Entity("UOrders.EFModel.OrderReview", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StarRating")
                        .IsRequired()
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderReviews");
                });

            modelBuilder.Entity("UOrders.EFModel.Price", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("MenuItemOptionValuePrice")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuItemPrice")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.HasKey("ID");

                    b.HasIndex("MenuItemOptionValuePrice");

                    b.HasIndex("MenuItemPrice");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("UOrders.EFModel.UOrdersUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("ConfirmationEmailSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UOrders.EFModel.UOrdersUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UOrders.EFModel.UOrdersUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UOrders.EFModel.UOrdersUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UOrders.EFModel.UOrdersUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UOrders.EFModel.LocalizedText", b =>
                {
                    b.HasOne("UOrders.EFModel.MenuCategory", "MenuCategoryDescription")
                        .WithMany("Description")
                        .HasForeignKey("MenuCategoryDescriptionID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("UOrders.EFModel.MenuCategory", "MenuCategoryTitle")
                        .WithMany("Title")
                        .HasForeignKey("MenuCategoryTitleID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("UOrders.EFModel.MenuItem", "MenuItemDescription")
                        .WithMany("Description")
                        .HasForeignKey("MenuItemDescriptionID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("UOrders.EFModel.MenuItemOption", "MenuItemOptionDescription")
                        .WithMany("Description")
                        .HasForeignKey("MenuItemOptionDescriptionID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("UOrders.EFModel.MenuItemOption", "MenuItemOptionName")
                        .WithMany("Name")
                        .HasForeignKey("MenuItemOptionNameID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("UOrders.EFModel.MenuItemOptionValue", "MenuItemOptionValueName")
                        .WithMany("Name")
                        .HasForeignKey("MenuItemOptionValueNameID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("UOrders.EFModel.MenuItem", "MenuItemTitle")
                        .WithMany("Title")
                        .HasForeignKey("MenuItemTitleID")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("MenuCategoryDescription");

                    b.Navigation("MenuCategoryTitle");

                    b.Navigation("MenuItemDescription");

                    b.Navigation("MenuItemOptionDescription");

                    b.Navigation("MenuItemOptionName");

                    b.Navigation("MenuItemOptionValueName");

                    b.Navigation("MenuItemTitle");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuItem", b =>
                {
                    b.HasOne("UOrders.EFModel.MenuCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuItemOption", b =>
                {
                    b.HasOne("UOrders.EFModel.MenuItem", null)
                        .WithMany("Options")
                        .HasForeignKey("MenuItemID");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuItemOptionValue", b =>
                {
                    b.HasOne("UOrders.EFModel.MenuItemOption", "MenuItemOption")
                        .WithMany("Values")
                        .HasForeignKey("MenuItemOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItemOption");
                });

            modelBuilder.Entity("UOrders.EFModel.Order", b =>
                {
                    b.HasOne("UOrders.EFModel.UOrdersUser", "OrderedBy")
                        .WithMany("Orders")
                        .HasForeignKey("OrderedById");

                    b.Navigation("OrderedBy");
                });

            modelBuilder.Entity("UOrders.EFModel.OrderItem", b =>
                {
                    b.HasOne("UOrders.EFModel.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UOrders.EFModel.Order", "Order")
                        .WithMany("OrderedItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("UOrders.EFModel.OrderItemCheckedOption", b =>
                {
                    b.HasOne("UOrders.EFModel.MenuItemOptionValue", "OptionValue")
                        .WithMany()
                        .HasForeignKey("OptionValueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UOrders.EFModel.OrderItem", "OrderItem")
                        .WithMany("CheckedOptions")
                        .HasForeignKey("OrderItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionValue");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("UOrders.EFModel.OrderReview", b =>
                {
                    b.HasOne("UOrders.EFModel.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("UOrders.EFModel.Price", b =>
                {
                    b.HasOne("UOrders.EFModel.MenuItemOptionValue", "MenuItemOptionValue")
                        .WithMany("PriceChangeToBase")
                        .HasForeignKey("MenuItemOptionValuePrice")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("UOrders.EFModel.MenuItem", "MenuItem")
                        .WithMany("Prices")
                        .HasForeignKey("MenuItemPrice")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("MenuItem");

                    b.Navigation("MenuItemOptionValue");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuCategory", b =>
                {
                    b.Navigation("Description");

                    b.Navigation("Items");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuItem", b =>
                {
                    b.Navigation("Description");

                    b.Navigation("Options");

                    b.Navigation("Prices");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuItemOption", b =>
                {
                    b.Navigation("Description");

                    b.Navigation("Name");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("UOrders.EFModel.MenuItemOptionValue", b =>
                {
                    b.Navigation("Name");

                    b.Navigation("PriceChangeToBase");
                });

            modelBuilder.Entity("UOrders.EFModel.Order", b =>
                {
                    b.Navigation("OrderedItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("UOrders.EFModel.OrderItem", b =>
                {
                    b.Navigation("CheckedOptions");
                });

            modelBuilder.Entity("UOrders.EFModel.UOrdersUser", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
