//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOrders.WebUI.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UOrders.WebUI.Properties.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiple selection ähnelt.
        /// </summary>
        public static string str_enum_menuitemoptiontype_multiselect {
            get {
                return ResourceManager.GetString("str_enum_menuitemoptiontype_multiselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection ähnelt.
        /// </summary>
        public static string str_enum_menuitemoptiontype_selection {
            get {
                return ResourceManager.GetString("str_enum_menuitemoptiontype_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit menu ähnelt.
        /// </summary>
        public static string str_nav_entry_admin {
            get {
                return ResourceManager.GetString("str_nav_entry_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string str_nav_entry_login {
            get {
                return ResourceManager.GetString("str_nav_entry_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        public static string str_nav_entry_logout {
            get {
                return ResourceManager.GetString("str_nav_entry_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu ähnelt.
        /// </summary>
        public static string str_nav_entry_menu {
            get {
                return ResourceManager.GetString("str_nav_entry_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My data ähnelt.
        /// </summary>
        public static string str_nav_entry_mydata {
            get {
                return ResourceManager.GetString("str_nav_entry_mydata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orders ähnelt.
        /// </summary>
        public static string str_nav_entry_orders {
            get {
                return ResourceManager.GetString("str_nav_entry_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string str_nav_entry_register {
            get {
                return ResourceManager.GetString("str_nav_entry_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string str_nav_entry_startpage {
            get {
                return ResourceManager.GetString("str_nav_entry_startpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User management ähnelt.
        /// </summary>
        public static string str_nav_entry_users {
            get {
                return ResourceManager.GetString("str_nav_entry_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit review ähnelt.
        /// </summary>
        public static string str_pg_addreview_btn_submit {
            get {
                return ResourceManager.GetString("str_pg_addreview_btn_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This link is not valid. Please check! ähnelt.
        /// </summary>
        public static string str_pg_addreview_err_noorderid {
            get {
                return ResourceManager.GetString("str_pg_addreview_err_noorderid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while submitting review. Please try again later. ähnelt.
        /// </summary>
        public static string str_pg_addreview_err_submit {
            get {
                return ResourceManager.GetString("str_pg_addreview_err_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you very much! Your review has been saved. ähnelt.
        /// </summary>
        public static string str_pg_addreview_succ_reviewadded {
            get {
                return ResourceManager.GetString("str_pg_addreview_succ_reviewadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Review ähnelt.
        /// </summary>
        public static string str_pg_addreview_title {
            get {
                return ResourceManager.GetString("str_pg_addreview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add category ähnelt.
        /// </summary>
        public static string str_pg_admin_btn_addcat {
            get {
                return ResourceManager.GetString("str_pg_admin_btn_addcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string str_pg_admin_cateditmod_btn_close {
            get {
                return ResourceManager.GetString("str_pg_admin_cateditmod_btn_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes ähnelt.
        /// </summary>
        public static string str_pg_admin_cateditmod_btn_save {
            get {
                return ResourceManager.GetString("str_pg_admin_cateditmod_btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string str_pg_admin_cateditmod_fldlbl_desc {
            get {
                return ResourceManager.GetString("str_pg_admin_cateditmod_fldlbl_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string str_pg_admin_cateditmod_fldlbl_title {
            get {
                return ResourceManager.GetString("str_pg_admin_cateditmod_fldlbl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a commonly unserstandable description ähnelt.
        /// </summary>
        public static string str_pg_admin_cateditmod_fldplhldr_desc {
            get {
                return ResourceManager.GetString("str_pg_admin_cateditmod_fldplhldr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a commonly unserstandable title ähnelt.
        /// </summary>
        public static string str_pg_admin_cateditmod_fldplhldr_title {
            get {
                return ResourceManager.GetString("str_pg_admin_cateditmod_fldplhldr_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit category &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string str_pg_admin_cateditmod_title {
            get {
                return ResourceManager.GetString("str_pg_admin_cateditmod_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should the object and all dependent objects really be deleted? ähnelt.
        /// </summary>
        public static string str_pg_admin_delmod_body {
            get {
                return ResourceManager.GetString("str_pg_admin_delmod_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string str_pg_admin_delmod_btn_cancel {
            get {
                return ResourceManager.GetString("str_pg_admin_delmod_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string str_pg_admin_delmod_btn_delete {
            get {
                return ResourceManager.GetString("str_pg_admin_delmod_btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm delete ähnelt.
        /// </summary>
        public static string str_pg_admin_delmod_title {
            get {
                return ResourceManager.GetString("str_pg_admin_delmod_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_btn_close {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_btn_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_btn_save {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add option ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_fldbtn_addopt {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_fldbtn_addopt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy options ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_fldbtn_copyopt {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_fldbtn_copyopt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_fldlbl_desc {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_fldlbl_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_fldlbl_opts {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_fldlbl_opts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_fldlbl_price {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_fldlbl_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_fldlbl_title {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_fldlbl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a commonly unserstandable description ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_fldplhldr_desc {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_fldplhldr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a commonly unserstandable title ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_fldplhldr_title {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_fldplhldr_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type: {0} ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_lstopts_lbl_opttype {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_lstopts_lbl_opttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price: {0} ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_lstopts_lbl_valprice {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_lstopts_lbl_valprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit item &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string str_pg_admin_itmeditmod_title {
            get {
                return ResourceManager.GetString("str_pg_admin_itmeditmod_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string str_pg_admin_opteditmod_btn_ok {
            get {
                return ResourceManager.GetString("str_pg_admin_opteditmod_btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string str_pg_admin_opteditmod_fldlbl_name {
            get {
                return ResourceManager.GetString("str_pg_admin_opteditmod_fldlbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string str_pg_admin_opteditmod_fldlbl_type {
            get {
                return ResourceManager.GetString("str_pg_admin_opteditmod_fldlbl_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a commonly unserstandable name ähnelt.
        /// </summary>
        public static string str_pg_admin_opteditmod_fldplhldr_name {
            get {
                return ResourceManager.GetString("str_pg_admin_opteditmod_fldplhldr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit option &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string str_pg_admin_opteditmod_title {
            get {
                return ResourceManager.GetString("str_pg_admin_opteditmod_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit menu ähnelt.
        /// </summary>
        public static string str_pg_admin_title {
            get {
                return ResourceManager.GetString("str_pg_admin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not authorized ähnelt.
        /// </summary>
        public static string str_pg_admin_txt_notauthorized {
            get {
                return ResourceManager.GetString("str_pg_admin_txt_notauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string str_pg_admin_valeditmod_btn_ok {
            get {
                return ResourceManager.GetString("str_pg_admin_valeditmod_btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string str_pg_admin_valeditmod_fldlbl_name {
            get {
                return ResourceManager.GetString("str_pg_admin_valeditmod_fldlbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price ähnelt.
        /// </summary>
        public static string str_pg_admin_valeditmod_fldlbl_price {
            get {
                return ResourceManager.GetString("str_pg_admin_valeditmod_fldlbl_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a commonly unserstandable name ähnelt.
        /// </summary>
        public static string str_pg_admin_valeditmod_fldplhldr_name {
            get {
                return ResourceManager.GetString("str_pg_admin_valeditmod_fldplhldr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit option value &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string str_pg_admin_valeditmod_title {
            get {
                return ResourceManager.GetString("str_pg_admin_valeditmod_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string str_pg_cart_btn_next {
            get {
                return ResourceManager.GetString("str_pg_cart_btn_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string str_pg_cart_btn_prev {
            get {
                return ResourceManager.GetString("str_pg_cart_btn_prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit order ähnelt.
        /// </summary>
        public static string str_pg_cart_btn_sendorder {
            get {
                return ResourceManager.GetString("str_pg_cart_btn_sendorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should &quot;{0}&quot; really be deleted? ähnelt.
        /// </summary>
        public static string str_pg_cart_delmod_body {
            get {
                return ResourceManager.GetString("str_pg_cart_delmod_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string str_pg_cart_delmod_btn_cancel {
            get {
                return ResourceManager.GetString("str_pg_cart_delmod_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string str_pg_cart_delmod_btn_delete {
            get {
                return ResourceManager.GetString("str_pg_cart_delmod_btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove entry? ähnelt.
        /// </summary>
        public static string str_pg_cart_delmod_title {
            get {
                return ResourceManager.GetString("str_pg_cart_delmod_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty cart ähnelt.
        /// </summary>
        public static string str_pg_cart_step_checkcart_btn_clear_all {
            get {
                return ResourceManager.GetString("str_pg_cart_step_checkcart_btn_clear_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slice, without cheese, etc. ähnelt.
        /// </summary>
        public static string str_pg_cart_step_checkcart_fldlbl_itmrem {
            get {
                return ResourceManager.GetString("str_pg_cart_step_checkcart_fldlbl_itmrem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check cart ähnelt.
        /// </summary>
        public static string str_pg_cart_step_checkcart_name {
            get {
                return ResourceManager.GetString("str_pg_cart_step_checkcart_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Review order ähnelt.
        /// </summary>
        public static string str_pg_cart_step_checkorder_name {
            get {
                return ResourceManager.GetString("str_pg_cart_step_checkorder_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        public static string str_pg_cart_step_complete_name {
            get {
                return ResourceManager.GetString("str_pg_cart_step_complete_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submitting order... ähnelt.
        /// </summary>
        public static string str_pg_cart_step_complete_txt_sending {
            get {
                return ResourceManager.GetString("str_pg_cart_step_complete_txt_sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order submitted. ähnelt.
        /// </summary>
        public static string str_pg_cart_step_complete_txt_sent {
            get {
                return ResourceManager.GetString("str_pg_cart_step_complete_txt_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail address ähnelt.
        /// </summary>
        public static string str_pg_cart_step_enterdetails_fldlbl_mail {
            get {
                return ResourceManager.GetString("str_pg_cart_step_enterdetails_fldlbl_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string str_pg_cart_step_enterdetails_fldlbl_name {
            get {
                return ResourceManager.GetString("str_pg_cart_step_enterdetails_fldlbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phone ähnelt.
        /// </summary>
        public static string str_pg_cart_step_enterdetails_fldplbl_phone {
            get {
                return ResourceManager.GetString("str_pg_cart_step_enterdetails_fldplbl_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remarks ähnelt.
        /// </summary>
        public static string str_pg_cart_step_enterdetails_fldplbl_rem {
            get {
                return ResourceManager.GetString("str_pg_cart_step_enterdetails_fldplbl_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die john.smith@example.com ähnelt.
        /// </summary>
        public static string str_pg_cart_step_enterdetails_fldplhldr_mail {
            get {
                return ResourceManager.GetString("str_pg_cart_step_enterdetails_fldplhldr_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your name... ähnelt.
        /// </summary>
        public static string str_pg_cart_step_enterdetails_fldplhldr_name {
            get {
                return ResourceManager.GetString("str_pg_cart_step_enterdetails_fldplhldr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Further notes on the order ähnelt.
        /// </summary>
        public static string str_pg_cart_step_enterdetails_fldpplhldr_rem {
            get {
                return ResourceManager.GetString("str_pg_cart_step_enterdetails_fldpplhldr_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter details ähnelt.
        /// </summary>
        public static string str_pg_cart_step_enterdetails_name {
            get {
                return ResourceManager.GetString("str_pg_cart_step_enterdetails_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cart ähnelt.
        /// </summary>
        public static string str_pg_cart_title {
            get {
                return ResourceManager.GetString("str_pg_cart_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string str_pg_login_btn_login {
            get {
                return ResourceManager.GetString("str_pg_login_btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string str_pg_login_fldplhldr_pass {
            get {
                return ResourceManager.GetString("str_pg_login_fldplhldr_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string str_pg_login_fldplhldr_user {
            get {
                return ResourceManager.GetString("str_pg_login_fldplhldr_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed. Check username and password. ähnelt.
        /// </summary>
        public static string str_pg_login_msg_loginfailed {
            get {
                return ResourceManager.GetString("str_pg_login_msg_loginfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username is required. ähnelt.
        /// </summary>
        public static string str_pg_login_msg_username_required {
            get {
                return ResourceManager.GetString("str_pg_login_msg_username_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User already taken! ähnelt.
        /// </summary>
        public static string str_pg_login_msg_username_taken {
            get {
                return ResourceManager.GetString("str_pg_login_msg_username_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username must be at least 2 characters long. ähnelt.
        /// </summary>
        public static string str_pg_login_msg_username_tooshort {
            get {
                return ResourceManager.GetString("str_pg_login_msg_username_tooshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string str_pg_login_title {
            get {
                return ResourceManager.GetString("str_pg_login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add {0} ähnelt.
        /// </summary>
        public static string str_pg_menu_itmmod_btn_addtocart {
            get {
                return ResourceManager.GetString("str_pg_menu_itmmod_btn_addtocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string str_pg_menu_itmmod_btn_cancel {
            get {
                return ResourceManager.GetString("str_pg_menu_itmmod_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ähnelt.
        /// </summary>
        public static string str_pg_menu_itmmod_fldlbl_count {
            get {
                return ResourceManager.GetString("str_pg_menu_itmmod_fldlbl_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remarks ähnelt.
        /// </summary>
        public static string str_pg_menu_itmmod_fldlbl_rem {
            get {
                return ResourceManager.GetString("str_pg_menu_itmmod_fldlbl_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter remarks here... ähnelt.
        /// </summary>
        public static string str_pg_menu_itmmod_fldplhldr_rem {
            get {
                return ResourceManager.GetString("str_pg_menu_itmmod_fldplhldr_rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu ähnelt.
        /// </summary>
        public static string str_pg_menu_title {
            get {
                return ResourceManager.GetString("str_pg_menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string str_pg_mydata_btn_update {
            get {
                return ResourceManager.GetString("str_pg_mydata_btn_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My data ähnelt.
        /// </summary>
        public static string str_pg_mydata_title {
            get {
                return ResourceManager.GetString("str_pg_mydata_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest orders ähnelt.
        /// </summary>
        public static string str_pg_orders_title {
            get {
                return ResourceManager.GetString("str_pg_orders_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No orders ähnelt.
        /// </summary>
        public static string str_pg_orders_txt_noorders {
            get {
                return ResourceManager.GetString("str_pg_orders_txt_noorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not authorized ähnelt.
        /// </summary>
        public static string str_pg_orders_txt_notauthorized {
            get {
                return ResourceManager.GetString("str_pg_orders_txt_notauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string str_pg_register_btn_register {
            get {
                return ResourceManager.GetString("str_pg_register_btn_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Password ähnelt.
        /// </summary>
        public static string str_pg_register_fldplhldr_confirmpass {
            get {
                return ResourceManager.GetString("str_pg_register_fldplhldr_confirmpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail address ähnelt.
        /// </summary>
        public static string str_pg_register_fldplhldr_mail {
            get {
                return ResourceManager.GetString("str_pg_register_fldplhldr_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string str_pg_register_fldplhldr_name {
            get {
                return ResourceManager.GetString("str_pg_register_fldplhldr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string str_pg_register_fldplhldr_pass {
            get {
                return ResourceManager.GetString("str_pg_register_fldplhldr_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phone ähnelt.
        /// </summary>
        public static string str_pg_register_fldplhldr_phone {
            get {
                return ResourceManager.GetString("str_pg_register_fldplhldr_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string str_pg_register_fldplhldr_user {
            get {
                return ResourceManager.GetString("str_pg_register_fldplhldr_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string str_pg_register_title {
            get {
                return ResourceManager.GetString("str_pg_register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User management ähnelt.
        /// </summary>
        public static string str_pg_users_title {
            get {
                return ResourceManager.GetString("str_pg_users_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not authorized ähnelt.
        /// </summary>
        public static string str_pg_users_txt_notauthorized {
            get {
                return ResourceManager.GetString("str_pg_users_txt_notauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en ähnelt.
        /// </summary>
        public static string str_sys_api_lang {
            get {
                return ResourceManager.GetString("str_sys_api_lang", resourceCulture);
            }
        }
    }
}
