name: Prune old docker images

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.PRUNE_DOCKER_TOKEN }}
          container: u-orders
          untagged: true
